"""Initial migration

Revision ID: a44a6dbf8a82
Revises: 
Create Date: 2025-07-03 23:19:09.013476

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a44a6dbf8a82'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('institucion_insumo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('IDInstitucion'))
        batch_op.drop_index(batch_op.f('IDInsumo'))

    op.drop_table('institucion_insumo')
    with op.batch_alter_table('eventos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('IDInstitucion'))

    op.drop_table('eventos')
    with op.batch_alter_table('usuarios_proyecto', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('IDProyecto'))
        batch_op.drop_index(batch_op.f('IDUsuarios'))

    op.drop_table('usuarios_proyecto')
    op.drop_table('encargado')
    with op.batch_alter_table('foros', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('IDProyecto'))

    op.drop_table('foros')
    op.drop_table('informacion')
    op.drop_table('publicacion')
    op.drop_table('estados')
    with op.batch_alter_table('foro_usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('IDForo'))
        batch_op.drop_index(batch_op.f('IDUsuarios'))

    op.drop_table('foro_usuarios')
    with op.batch_alter_table('equipamiento_lab', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('IDEquipamiento'))
        batch_op.drop_index(batch_op.f('IDLaboratorio'))

    op.drop_table('equipamiento_lab')
    with op.batch_alter_table('servicio_lab', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('IDLaboratorio'))
        batch_op.drop_index(batch_op.f('IDServicios'))

    op.drop_table('servicio_lab')
    with op.batch_alter_table('convocatorias', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('IDInstitucion'))

    op.drop_table('convocatorias')
    op.drop_table('estatus')
    op.drop_table('proyecto_financiamiento')
    op.drop_table('equipamiento')
    with op.batch_alter_table('insumo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('IDEncargado'))
        batch_op.drop_index(batch_op.f('IDTipoInsumo'))

    op.drop_table('insumo')
    with op.batch_alter_table('actividad', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_actividad_usuario'))

    op.drop_table('actividad')
    op.drop_table('proyecto')
    op.drop_table('servicio')
    op.drop_table('financiamiento')
    op.drop_table('colonias')
    op.drop_table('investigador')
    op.drop_table('municipios')
    op.drop_table('tipo_insumo')
    with op.batch_alter_table('permiso', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('nombre'))

    op.drop_table('permiso')
    op.drop_table('tipo_usuario')
    with op.batch_alter_table('proyecto_investigadores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('IDInvestigador'))
        batch_op.drop_index(batch_op.f('IDProyecto'))

    op.drop_table('proyecto_investigadores')
    with op.batch_alter_table('area', schema=None) as batch_op:
        batch_op.alter_column('id_area',
               existing_type=mysql.BIGINT(display_width=20),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('creado_por',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('modificado_por',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)

    with op.batch_alter_table('institucion', schema=None) as batch_op:
        batch_op.alter_column('id_institucion',
               existing_type=mysql.BIGINT(display_width=20),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('nombre_institucion',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('calle',
               existing_type=mysql.VARCHAR(length=35),
               type_=sa.String(length=200),
               nullable=True)
        batch_op.alter_column('colonia',
               existing_type=mysql.VARCHAR(length=35),
               type_=sa.String(length=200),
               nullable=True)
        batch_op.alter_column('municipio',
               existing_type=mysql.VARCHAR(length=35),
               type_=sa.String(length=200),
               nullable=True)
        batch_op.alter_column('estado',
               existing_type=mysql.VARCHAR(length=35),
               type_=sa.String(length=200),
               nullable=True)
        batch_op.alter_column('codigo_postal',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=20),
               nullable=True)
        batch_op.alter_column('telefono',
               existing_type=mysql.VARCHAR(length=14),
               type_=sa.String(length=20),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('fecha_registro',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               nullable=True)
        batch_op.alter_column('activo',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
        batch_op.alter_column('id_tipo_institucion',
               existing_type=mysql.BIGINT(display_width=20),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('IDEncargado'))
        batch_op.drop_index(batch_op.f('IDTipoInstitucion'))
        batch_op.create_foreign_key(None, 'tipo_institucion', ['id_tipo_institucion'], ['id_tipo_institucion'])
        batch_op.drop_column('fecha_modificacion')
        batch_op.drop_column('numero')
        batch_op.drop_column('id_encargado')

    with op.batch_alter_table('laboratorio', schema=None) as batch_op:
        batch_op.alter_column('disponibilidad',
               existing_type=mysql.ENUM('Activo', 'Inactivo', 'Mantenimiento', 'Reservado'),
               type_=sa.String(length=100),
               existing_nullable=True,
               existing_server_default=sa.text("'Activo'"))
        batch_op.alter_column('descripcion',
               existing_type=mysql.TEXT(),
               nullable=True)
        batch_op.alter_column('imagen_url',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('capacidad',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='Número máximo de personas que pueden usar el laboratorio',
               existing_nullable=True,
               existing_server_default=sa.text('20'))
        batch_op.alter_column('horario',
               existing_type=mysql.VARCHAR(length=100),
               comment=None,
               existing_comment='Horario de disponibilidad (ej: Lunes a Viernes 8:00-18:00)',
               existing_nullable=True)
        batch_op.alter_column('ubicacion',
               existing_type=mysql.VARCHAR(length=200),
               comment=None,
               existing_comment='Ubicación específica del laboratorio (edificio, piso, aula)',
               existing_nullable=True)
        batch_op.alter_column('telefono',
               existing_type=mysql.VARCHAR(length=20),
               comment=None,
               existing_comment='Teléfono de contacto del laboratorio',
               existing_nullable=True)
        batch_op.alter_column('email_contacto',
               existing_type=mysql.VARCHAR(length=100),
               comment=None,
               existing_comment='Email de contacto del laboratorio',
               existing_nullable=True)
        batch_op.alter_column('superficie_m2',
               existing_type=mysql.DECIMAL(precision=8, scale=2),
               comment=None,
               existing_comment='Superficie en metros cuadrados',
               existing_nullable=True)
        batch_op.alter_column('equipamiento',
               existing_type=mysql.TEXT(),
               comment=None,
               existing_comment='Lista de equipamiento disponible (separado por comas)',
               existing_nullable=True)
        batch_op.alter_column('normas_uso',
               existing_type=mysql.TEXT(),
               comment=None,
               existing_comment='Normas y reglas de uso del laboratorio',
               existing_nullable=True)
        batch_op.alter_column('requiere_capacitacion',
               existing_type=mysql.TINYINT(display_width=1),
               comment=None,
               existing_comment='Si requiere capacitación previa para usar',
               existing_nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('id_institucion',
               existing_type=mysql.BIGINT(display_width=20),
               nullable=True)
        batch_op.alter_column('id_area',
               existing_type=mysql.BIGINT(display_width=20),
               nullable=True)
        batch_op.alter_column('id_tipo_laboratorio',
               existing_type=mysql.BIGINT(display_width=20),
               nullable=True)
        batch_op.alter_column('id_encargado',
               existing_type=mysql.BIGINT(display_width=20),
               nullable=True)
        batch_op.drop_index(batch_op.f('IDArea'))
        batch_op.drop_index(batch_op.f('IDEncargado'))
        batch_op.drop_index(batch_op.f('IDInstitucion'))
        batch_op.drop_index(batch_op.f('IDTipoLaboratorio'))
        batch_op.drop_index(batch_op.f('idx_area'))
        batch_op.drop_index(batch_op.f('idx_disponibilidad'))
        batch_op.drop_index(batch_op.f('idx_institucion'))
        batch_op.drop_constraint(batch_op.f('fk_laboratorio_institucion'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_laboratorio_area'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_laboratorio_tipo'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'tipo_laboratorio', ['id_tipo_laboratorio'], ['id_tipo_laboratorio'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'institucion', ['id_institucion'], ['id_institucion'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'area', ['id_area'], ['id_area'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'usuario', ['id_encargado'], ['id_usuario'], ondelete='SET NULL')

    with op.batch_alter_table('permisos', schema=None) as batch_op:
        batch_op.alter_column('leer',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
        batch_op.alter_column('actualizar',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
        batch_op.alter_column('crear',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
        batch_op.alter_column('borrar',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
        batch_op.create_unique_constraint(None, ['nombre_permiso'])

    with op.batch_alter_table('permisos_rol', schema=None) as batch_op:
        batch_op.alter_column('id_permiso',
               existing_type=mysql.BIGINT(display_width=20),
               nullable=True)
        batch_op.alter_column('id_rol',
               existing_type=mysql.BIGINT(display_width=20),
               nullable=True)

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.alter_column('descripcion',
               existing_type=mysql.TEXT(),
               nullable=True)
        batch_op.create_unique_constraint(None, ['nombre_rol'])

    with op.batch_alter_table('solicitud', schema=None) as batch_op:
        batch_op.alter_column('id_solicitud',
               existing_type=mysql.BIGINT(display_width=20),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('id_institucion',
               existing_type=mysql.BIGINT(display_width=20),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.alter_column('id_estatus',
               existing_type=mysql.BIGINT(display_width=20),
               type_=sa.Integer(),
               existing_nullable=False,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('id_tipo_solicitud',
               existing_type=mysql.BIGINT(display_width=20),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.alter_column('id_insumo',
               existing_type=mysql.BIGINT(display_width=20),
               type_=sa.Integer(),
               nullable=True)
        batch_op.alter_column('id_laboratorio',
               existing_type=mysql.BIGINT(display_width=20),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.alter_column('prioridad',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
        batch_op.drop_index(batch_op.f('IDEstatus'))
        batch_op.drop_index(batch_op.f('IDInstitucion'))
        batch_op.drop_index(batch_op.f('IDInsumo'))
        batch_op.drop_index(batch_op.f('IDInvestigador'))
        batch_op.drop_index(batch_op.f('IDLaboratorio'))
        batch_op.drop_index(batch_op.f('IDTipoSolicitud'))
        batch_op.drop_index(batch_op.f('idx_fecha_solicitud'))
        batch_op.drop_constraint(batch_op.f('fk_solicitud_estatus'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_solicitud_insumo'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_solicitud_investigador'), type_='foreignkey')
        batch_op.drop_column('hora_inicio')
        batch_op.drop_column('num_personas')
        batch_op.drop_column('id_investigador')
        batch_op.drop_column('hora_fin')

    with op.batch_alter_table('solicitud_usuarios', schema=None) as batch_op:
        batch_op.alter_column('id_solicitud_usuarios',
               existing_type=mysql.BIGINT(display_width=20),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('id_solicitud',
               existing_type=mysql.BIGINT(display_width=20),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.alter_column('id_usuario',
               existing_type=mysql.BIGINT(display_width=20),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('IDSolicitud'))
        batch_op.drop_index(batch_op.f('IDUsuarios'))

    with op.batch_alter_table('tipo_institucion', schema=None) as batch_op:
        batch_op.alter_column('id_tipo_institucion',
               existing_type=mysql.BIGINT(display_width=20),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
        batch_op.drop_column('descripcion')

    with op.batch_alter_table('tipo_laboratorio', schema=None) as batch_op:
        batch_op.alter_column('descripcion',
               existing_type=mysql.TEXT(),
               nullable=True)

    with op.batch_alter_table('tipo_solicitud', schema=None) as batch_op:
        batch_op.add_column(sa.Column('require_aprobacion', sa.Boolean(), nullable=False))
        batch_op.alter_column('descripcion',
               existing_type=mysql.TEXT(),
               nullable=True)
        batch_op.drop_column('requiere_aprobacion')

    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.alter_column('id_usuario',
               existing_type=mysql.BIGINT(display_width=20),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('username',
               existing_type=mysql.VARCHAR(length=35),
               type_=sa.String(length=80),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=128),
               nullable=True)
        batch_op.alter_column('nombre',
               existing_type=mysql.VARCHAR(length=35),
               type_=sa.String(length=100),
               nullable=True)
        batch_op.alter_column('apellido_paterno',
               existing_type=mysql.VARCHAR(length=35),
               type_=sa.String(length=100),
               nullable=True)
        batch_op.alter_column('apellido_materno',
               existing_type=mysql.VARCHAR(length=35),
               type_=sa.String(length=100),
               nullable=True)
        batch_op.alter_column('telefono',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('fecha_registro',
               existing_type=mysql.DATETIME(),
               nullable=True)
        batch_op.alter_column('activo',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
        batch_op.alter_column('fecha_creacion',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               nullable=True)
        batch_op.alter_column('fecha_modificacion',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               nullable=True)
        batch_op.alter_column('ultimo_acceso',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               nullable=True)
        batch_op.alter_column('id_institucion',
               existing_type=mysql.BIGINT(display_width=20),
               type_=sa.Integer(),
               nullable=True)
        batch_op.alter_column('id_area',
               existing_type=mysql.BIGINT(display_width=20),
               type_=sa.Integer(),
               nullable=True)
        batch_op.alter_column('id_rol',
               existing_type=mysql.BIGINT(display_width=20),
               type_=sa.Integer(),
               nullable=True)
        batch_op.drop_index(batch_op.f('IDUsuario'))
        batch_op.create_unique_constraint(None, ['email'])
        batch_op.create_foreign_key(None, 'roles', ['id_rol'], ['id_rol'])
        batch_op.create_foreign_key(None, 'institucion', ['id_institucion'], ['id_institucion'])
        batch_op.drop_column('rol_adicional')
        batch_op.drop_column('ultima_actualizacion_password')
        batch_op.drop_column('fecha_cambio')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_cambio', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=False))
        batch_op.add_column(sa.Column('ultima_actualizacion_password', mysql.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('rol_adicional', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index(batch_op.f('IDUsuario'), ['id_usuario'], unique=True)
        batch_op.alter_column('id_rol',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(display_width=20),
               nullable=False)
        batch_op.alter_column('id_area',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(display_width=20),
               nullable=False)
        batch_op.alter_column('id_institucion',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(display_width=20),
               nullable=False)
        batch_op.alter_column('ultimo_acceso',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               nullable=False)
        batch_op.alter_column('fecha_modificacion',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               nullable=False)
        batch_op.alter_column('fecha_creacion',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               nullable=False)
        batch_op.alter_column('activo',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
        batch_op.alter_column('fecha_registro',
               existing_type=mysql.DATETIME(),
               nullable=False)
        batch_op.alter_column('telefono',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('apellido_materno',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=35),
               nullable=False)
        batch_op.alter_column('apellido_paterno',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=35),
               nullable=False)
        batch_op.alter_column('nombre',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=35),
               nullable=False)
        batch_op.alter_column('password',
               existing_type=sa.String(length=128),
               type_=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.String(length=120),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.String(length=80),
               type_=mysql.VARCHAR(length=35),
               existing_nullable=False)
        batch_op.alter_column('id_usuario',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(display_width=20),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('tipo_solicitud', schema=None) as batch_op:
        batch_op.add_column(sa.Column('requiere_aprobacion', mysql.TINYINT(display_width=1), server_default=sa.text('1'), autoincrement=False, nullable=False))
        batch_op.alter_column('descripcion',
               existing_type=mysql.TEXT(),
               nullable=False)
        batch_op.drop_column('require_aprobacion')

    with op.batch_alter_table('tipo_laboratorio', schema=None) as batch_op:
        batch_op.alter_column('descripcion',
               existing_type=mysql.TEXT(),
               nullable=False)

    with op.batch_alter_table('tipo_institucion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descripcion', mysql.TEXT(), nullable=False))
        batch_op.alter_column('id_tipo_institucion',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(display_width=20),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('solicitud_usuarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('IDUsuarios'), ['id_usuario'], unique=False)
        batch_op.create_index(batch_op.f('IDSolicitud'), ['id_solicitud'], unique=False)
        batch_op.alter_column('id_usuario',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(display_width=20),
               existing_nullable=False)
        batch_op.alter_column('id_solicitud',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(display_width=20),
               existing_nullable=False)
        batch_op.alter_column('id_solicitud_usuarios',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(display_width=20),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('solicitud', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hora_fin', mysql.TIME(), nullable=True, comment='Hora de fin de la solicitud'))
        batch_op.add_column(sa.Column('id_investigador', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('num_personas', mysql.INTEGER(display_width=11), server_default=sa.text('1'), autoincrement=False, nullable=True, comment='Número de personas que usarán el laboratorio'))
        batch_op.add_column(sa.Column('hora_inicio', mysql.TIME(), nullable=True, comment='Hora de inicio de la solicitud'))
        batch_op.create_foreign_key(batch_op.f('fk_solicitud_investigador'), 'investigador', ['id_investigador'], ['id_investigador'])
        batch_op.create_foreign_key(batch_op.f('fk_solicitud_insumo'), 'insumo', ['id_insumo'], ['id_insumo'])
        batch_op.create_foreign_key(batch_op.f('fk_solicitud_estatus'), 'estatus', ['id_estatus'], ['id_estatus'])
        batch_op.create_index(batch_op.f('idx_fecha_solicitud'), ['fecha_solicitud'], unique=False)
        batch_op.create_index(batch_op.f('IDTipoSolicitud'), ['id_tipo_solicitud'], unique=False)
        batch_op.create_index(batch_op.f('IDLaboratorio'), ['id_laboratorio'], unique=False)
        batch_op.create_index(batch_op.f('IDInvestigador'), ['id_investigador'], unique=False)
        batch_op.create_index(batch_op.f('IDInsumo'), ['id_insumo'], unique=False)
        batch_op.create_index(batch_op.f('IDInstitucion'), ['id_institucion'], unique=False)
        batch_op.create_index(batch_op.f('IDEstatus'), ['id_estatus'], unique=False)
        batch_op.alter_column('prioridad',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('id_laboratorio',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(display_width=20),
               existing_nullable=False)
        batch_op.alter_column('id_insumo',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(display_width=20),
               nullable=False)
        batch_op.alter_column('id_tipo_solicitud',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(display_width=20),
               existing_nullable=False)
        batch_op.alter_column('id_estatus',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(display_width=20),
               existing_nullable=False,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('id_institucion',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(display_width=20),
               existing_nullable=False)
        batch_op.alter_column('id_solicitud',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(display_width=20),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('descripcion',
               existing_type=mysql.TEXT(),
               nullable=False)

    with op.batch_alter_table('permisos_rol', schema=None) as batch_op:
        batch_op.alter_column('id_rol',
               existing_type=mysql.BIGINT(display_width=20),
               nullable=False)
        batch_op.alter_column('id_permiso',
               existing_type=mysql.BIGINT(display_width=20),
               nullable=False)

    with op.batch_alter_table('permisos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('borrar',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
        batch_op.alter_column('crear',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
        batch_op.alter_column('actualizar',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
        batch_op.alter_column('leer',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)

    with op.batch_alter_table('laboratorio', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_laboratorio_tipo'), 'tipo_laboratorio', ['id_tipo_laboratorio'], ['id_tipo_laboratorio'])
        batch_op.create_foreign_key(batch_op.f('fk_laboratorio_area'), 'area', ['id_area'], ['id_area'])
        batch_op.create_foreign_key(batch_op.f('fk_laboratorio_institucion'), 'institucion', ['id_institucion'], ['id_institucion'])
        batch_op.create_index(batch_op.f('idx_institucion'), ['id_institucion'], unique=False)
        batch_op.create_index(batch_op.f('idx_disponibilidad'), ['disponibilidad'], unique=False)
        batch_op.create_index(batch_op.f('idx_area'), ['id_area'], unique=False)
        batch_op.create_index(batch_op.f('IDTipoLaboratorio'), ['id_tipo_laboratorio'], unique=False)
        batch_op.create_index(batch_op.f('IDInstitucion'), ['id_institucion'], unique=False)
        batch_op.create_index(batch_op.f('IDEncargado'), ['id_encargado'], unique=False)
        batch_op.create_index(batch_op.f('IDArea'), ['id_area'], unique=False)
        batch_op.alter_column('id_encargado',
               existing_type=mysql.BIGINT(display_width=20),
               nullable=False)
        batch_op.alter_column('id_tipo_laboratorio',
               existing_type=mysql.BIGINT(display_width=20),
               nullable=False)
        batch_op.alter_column('id_area',
               existing_type=mysql.BIGINT(display_width=20),
               nullable=False)
        batch_op.alter_column('id_institucion',
               existing_type=mysql.BIGINT(display_width=20),
               nullable=False)
        batch_op.alter_column('requiere_capacitacion',
               existing_type=mysql.TINYINT(display_width=1),
               comment='Si requiere capacitación previa para usar',
               existing_nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('normas_uso',
               existing_type=mysql.TEXT(),
               comment='Normas y reglas de uso del laboratorio',
               existing_nullable=True)
        batch_op.alter_column('equipamiento',
               existing_type=mysql.TEXT(),
               comment='Lista de equipamiento disponible (separado por comas)',
               existing_nullable=True)
        batch_op.alter_column('superficie_m2',
               existing_type=mysql.DECIMAL(precision=8, scale=2),
               comment='Superficie en metros cuadrados',
               existing_nullable=True)
        batch_op.alter_column('email_contacto',
               existing_type=mysql.VARCHAR(length=100),
               comment='Email de contacto del laboratorio',
               existing_nullable=True)
        batch_op.alter_column('telefono',
               existing_type=mysql.VARCHAR(length=20),
               comment='Teléfono de contacto del laboratorio',
               existing_nullable=True)
        batch_op.alter_column('ubicacion',
               existing_type=mysql.VARCHAR(length=200),
               comment='Ubicación específica del laboratorio (edificio, piso, aula)',
               existing_nullable=True)
        batch_op.alter_column('horario',
               existing_type=mysql.VARCHAR(length=100),
               comment='Horario de disponibilidad (ej: Lunes a Viernes 8:00-18:00)',
               existing_nullable=True)
        batch_op.alter_column('capacidad',
               existing_type=mysql.INTEGER(display_width=11),
               comment='Número máximo de personas que pueden usar el laboratorio',
               existing_nullable=True,
               existing_server_default=sa.text('20'))
        batch_op.alter_column('imagen_url',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('descripcion',
               existing_type=mysql.TEXT(),
               nullable=False)
        batch_op.alter_column('disponibilidad',
               existing_type=sa.String(length=100),
               type_=mysql.ENUM('Activo', 'Inactivo', 'Mantenimiento', 'Reservado'),
               existing_nullable=True,
               existing_server_default=sa.text("'Activo'"))

    with op.batch_alter_table('institucion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_encargado', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('numero', mysql.INTEGER(display_width=15), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('fecha_modificacion', sa.DATE(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index(batch_op.f('IDTipoInstitucion'), ['id_tipo_institucion'], unique=False)
        batch_op.create_index(batch_op.f('IDEncargado'), ['id_encargado'], unique=False)
        batch_op.alter_column('id_tipo_institucion',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(display_width=20),
               existing_nullable=False)
        batch_op.alter_column('activo',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
        batch_op.alter_column('fecha_registro',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('telefono',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=14),
               nullable=False)
        batch_op.alter_column('codigo_postal',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('estado',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(length=35),
               nullable=False)
        batch_op.alter_column('municipio',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(length=35),
               nullable=False)
        batch_op.alter_column('colonia',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(length=35),
               nullable=False)
        batch_op.alter_column('calle',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(length=35),
               nullable=False)
        batch_op.alter_column('nombre_institucion',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.alter_column('id_institucion',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(display_width=20),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('area', schema=None) as batch_op:
        batch_op.alter_column('modificado_por',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('creado_por',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('id_area',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(display_width=20),
               existing_nullable=False,
               autoincrement=True)

    op.create_table('proyecto_investigadores',
    sa.Column('id_proyecto_investigador', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False),
    sa.Column('id_proyecto', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False),
    sa.Column('id_investigador', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False),
    sa.Column('rol_investigador', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_investigador'], ['investigador.id_investigador'], name=op.f('fk_proyecto_investigadores_investigador')),
    sa.ForeignKeyConstraint(['id_proyecto'], ['proyecto.id_proyecto'], name=op.f('fk_proyecto_investigadores_proyecto')),
    sa.PrimaryKeyConstraint('id_proyecto_investigador'),
    mysql_collate='utf8mb3_general_ci',
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('proyecto_investigadores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('IDProyecto'), ['id_proyecto'], unique=False)
        batch_op.create_index(batch_op.f('IDInvestigador'), ['id_investigador'], unique=False)

    op.create_table('tipo_usuario',
    sa.Column('id_tipo_usuario', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('nombre_tipo_usuario', mysql.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id_tipo_usuario'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('permiso',
    sa.Column('id_permiso', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('nombre', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('descripcion', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id_permiso'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('permiso', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('nombre'), ['nombre'], unique=True)

    op.create_table('tipo_insumo',
    sa.Column('id_tipo_insumo', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False),
    sa.Column('nombre_tipo_insumo', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('descripcion', mysql.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id_tipo_insumo'),
    mysql_collate='utf8mb3_general_ci',
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    op.create_table('municipios',
    sa.Column('id_municipio', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('nombre_municipio', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('id_estado', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_estado'], ['estados.id_estado'], name='municipios_ibfk_1'),
    sa.PrimaryKeyConstraint('id_municipio'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('investigador',
    sa.Column('id_investigador', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False),
    sa.Column('nombre_investigador', mysql.VARCHAR(length=35), nullable=False),
    sa.Column('apellido_paterno', mysql.VARCHAR(length=35), nullable=False),
    sa.Column('apellido_materno', mysql.VARCHAR(length=35), nullable=False),
    sa.Column('biografia', mysql.TEXT(), nullable=False),
    sa.Column('correo', mysql.VARCHAR(length=35), nullable=False),
    sa.Column('telefono', mysql.VARCHAR(length=14), nullable=False),
    sa.Column('fotografia', sa.BLOB(), nullable=False),
    sa.Column('id_institucion', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('id_area', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False),
    sa.Column('orcid_id', mysql.VARCHAR(length=500), nullable=False),
    sa.Column('fecha_creacion', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=True),
    sa.Column('fecha_modificacion', mysql.DATETIME(), server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'), nullable=True),
    sa.ForeignKeyConstraint(['id_area'], ['area.id_area'], name=op.f('fk_investigador_area')),
    sa.ForeignKeyConstraint(['id_institucion'], ['institucion.id_institucion'], name=op.f('fk_investigador_institucion')),
    sa.PrimaryKeyConstraint('id_investigador'),
    mysql_collate='utf8mb3_general_ci',
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    op.create_table('colonias',
    sa.Column('id_colonia', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('nombre_colonia', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('id_municipio', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_municipio'], ['municipios.id_municipio'], name=op.f('colonias_ibfk_1')),
    sa.PrimaryKeyConstraint('id_colonia'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('financiamiento',
    sa.Column('id_financiamiento', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False),
    sa.Column('fuente', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('tipo', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('monto', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('fecha_asignacion', sa.DATE(), nullable=False),
    sa.Column('activo', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('fecha_vencimiento', sa.DATE(), nullable=False),
    sa.Column('fecha_creacion', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=True),
    sa.Column('fecha_modificacion', mysql.DATETIME(), server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'), nullable=True),
    sa.Column('id_institucion', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_institucion'], ['institucion.id_institucion'], name='fk_financiamiento_institucion'),
    sa.PrimaryKeyConstraint('id_financiamiento'),
    mysql_collate='utf8mb3_general_ci',
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    op.create_table('servicio',
    sa.Column('id_servicio', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False),
    sa.Column('nombre_servicio', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('activo', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('fecha_creacion', sa.DATE(), nullable=False),
    sa.PrimaryKeyConstraint('id_servicio'),
    mysql_collate='utf8mb3_general_ci',
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    op.create_table('proyecto',
    sa.Column('id_proyecto', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False),
    sa.Column('nombre_proyecto', mysql.VARCHAR(length=300), nullable=False),
    sa.Column('resumen', mysql.TEXT(), nullable=False),
    sa.Column('adjunto', mysql.BIT(length=1), nullable=False),
    sa.Column('fecha', sa.DATE(), nullable=False),
    sa.Column('tipo_proyecto', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('estatus', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('fecha_creacion', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=True),
    sa.Column('fecha_modificacion', mysql.DATETIME(), server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'), nullable=True),
    sa.PrimaryKeyConstraint('id_proyecto'),
    mysql_collate='utf8mb3_general_ci',
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    op.create_table('actividad',
    sa.Column('id_actividad', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False),
    sa.Column('id_usuario', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False),
    sa.Column('tipo', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('descripcion', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('fecha', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], name=op.f('actividad_ibfk_1')),
    sa.PrimaryKeyConstraint('id_actividad'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('actividad', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_actividad_usuario'), ['id_usuario'], unique=False)

    op.create_table('insumo',
    sa.Column('id_insumo', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False),
    sa.Column('nombre_insumo', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('descripcion', mysql.TEXT(), nullable=False),
    sa.Column('id_tipo_insumo', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False),
    sa.Column('id_encargado', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False),
    sa.Column('fecha_creacion', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=True),
    sa.Column('fecha_modificacion', mysql.DATETIME(), server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'), nullable=True),
    sa.ForeignKeyConstraint(['id_tipo_insumo'], ['tipo_insumo.id_tipo_insumo'], name='fk_insumo_tipo_insumo'),
    sa.PrimaryKeyConstraint('id_insumo'),
    mysql_collate='utf8mb3_general_ci',
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('insumo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('IDTipoInsumo'), ['id_tipo_insumo'], unique=False)
        batch_op.create_index(batch_op.f('IDEncargado'), ['id_encargado'], unique=False)

    op.create_table('equipamiento',
    sa.Column('id_equipamiento', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False),
    sa.Column('nombre_equipo', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('descripcion', mysql.TEXT(), nullable=False),
    sa.Column('fecha_creacion', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=True),
    sa.Column('fecha_modificacion', mysql.DATETIME(), server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'), nullable=True),
    sa.PrimaryKeyConstraint('id_equipamiento'),
    mysql_collate='utf8mb3_general_ci',
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    op.create_table('proyecto_financiamiento',
    sa.Column('id_proyecto_financiamiento', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False),
    sa.Column('id_financiamiento', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False),
    sa.Column('id_proyecto', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_financiamiento'], ['financiamiento.id_financiamiento'], name=op.f('fk_proyecto_financiamiento_financiamiento')),
    sa.ForeignKeyConstraint(['id_proyecto'], ['proyecto.id_proyecto'], name=op.f('fk_proyecto_financiamiento_proyecto')),
    sa.PrimaryKeyConstraint('id_proyecto_financiamiento'),
    mysql_collate='utf8mb3_general_ci',
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    op.create_table('estatus',
    sa.Column('id_estatus', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False),
    sa.Column('nombre_estatus', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('descripcion', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('color', mysql.VARCHAR(length=7), server_default=sa.text("'#6c757d'"), nullable=False, comment='Color hexadecimal para mostrar en UI'),
    sa.PrimaryKeyConstraint('id_estatus'),
    mysql_collate='utf8mb3_general_ci',
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    op.create_table('convocatorias',
    sa.Column('id_convocatoria', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False),
    sa.Column('nombre', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('tipo_convocatoria', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('fecha_inicio', sa.DATE(), nullable=False),
    sa.Column('fecha_fin', sa.DATE(), nullable=False),
    sa.Column('detalles', mysql.TEXT(), nullable=False),
    sa.Column('id_institucion', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False),
    sa.Column('fecha_creacion', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=True),
    sa.Column('fecha_modificacion', mysql.DATETIME(), server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'), nullable=True),
    sa.ForeignKeyConstraint(['id_institucion'], ['institucion.id_institucion'], name=op.f('fk_convocatorias_institucion')),
    sa.PrimaryKeyConstraint('id_convocatoria'),
    mysql_collate='utf8mb3_general_ci',
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('convocatorias', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('IDInstitucion'), ['id_institucion'], unique=False)

    op.create_table('servicio_lab',
    sa.Column('id_servicio_lab', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False),
    sa.Column('id_laboratorio', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False),
    sa.Column('id_servicio', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False),
    sa.Column('accesibilidad', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_laboratorio'], ['laboratorio.id_laboratorio'], name=op.f('fk_servicio_lab_laboratorio')),
    sa.ForeignKeyConstraint(['id_servicio'], ['servicio.id_servicio'], name=op.f('fk_servicio_lab_servicio')),
    sa.PrimaryKeyConstraint('id_servicio_lab'),
    mysql_collate='utf8mb3_general_ci',
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('servicio_lab', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('IDServicios'), ['id_servicio'], unique=False)
        batch_op.create_index(batch_op.f('IDLaboratorio'), ['id_laboratorio'], unique=False)

    op.create_table('equipamiento_lab',
    sa.Column('id_equipo_lab', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False),
    sa.Column('id_laboratorio', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False),
    sa.Column('id_equipamiento', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False),
    sa.Column('cantidad', mysql.INTEGER(display_width=5), autoincrement=False, nullable=False),
    sa.Column('capacidad', mysql.INTEGER(display_width=5), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_equipamiento'], ['equipamiento.id_equipamiento'], name=op.f('fk_equipamiento_lab_equipamiento')),
    sa.ForeignKeyConstraint(['id_laboratorio'], ['laboratorio.id_laboratorio'], name=op.f('fk_equipamiento_lab_laboratorio')),
    sa.PrimaryKeyConstraint('id_equipo_lab'),
    mysql_collate='utf8mb3_general_ci',
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('equipamiento_lab', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('IDLaboratorio'), ['id_laboratorio'], unique=False)
        batch_op.create_index(batch_op.f('IDEquipamiento'), ['id_equipamiento'], unique=False)

    op.create_table('foro_usuarios',
    sa.Column('id_foro_usuario', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False),
    sa.Column('id_foro', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False),
    sa.Column('id_usuario', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False),
    sa.Column('fecha_participacion', sa.DATE(), nullable=False),
    sa.ForeignKeyConstraint(['id_foro'], ['foros.id_foro'], name=op.f('fk_foro_usuarios_foro')),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], name=op.f('fk_foro_usuarios_usuario')),
    sa.PrimaryKeyConstraint('id_foro_usuario'),
    mysql_collate='utf8mb3_general_ci',
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('foro_usuarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('IDUsuarios'), ['id_usuario'], unique=False)
        batch_op.create_index(batch_op.f('IDForo'), ['id_foro'], unique=False)

    op.create_table('estados',
    sa.Column('id_estado', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('nombre_estado', mysql.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id_estado'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('publicacion',
    sa.Column('id_publicacion', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False),
    sa.Column('titulo', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('tipo', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('fecha_publicacion', sa.DATE(), nullable=False),
    sa.Column('url', mysql.VARCHAR(length=80), nullable=False),
    sa.Column('fecha_creacion', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=True),
    sa.Column('fecha_modificacion', mysql.DATETIME(), server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'), nullable=True),
    sa.Column('id_proyecto', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_proyecto'], ['proyecto.id_proyecto'], name=op.f('fk_publicacion_proyecto')),
    sa.PrimaryKeyConstraint('id_publicacion'),
    mysql_collate='utf8mb3_general_ci',
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    op.create_table('informacion',
    sa.Column('id_informacion', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False),
    sa.Column('titulo', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('descripcion', mysql.TEXT(), nullable=False),
    sa.Column('imagen', sa.BLOB(), nullable=False),
    sa.Column('tipo', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('fecha_creacion', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=True),
    sa.Column('fecha_modificacion', mysql.DATETIME(), server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'), nullable=True),
    sa.PrimaryKeyConstraint('id_informacion'),
    mysql_collate='utf8mb3_general_ci',
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    op.create_table('foros',
    sa.Column('id_foro', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False),
    sa.Column('nombre_foro', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('descripcion', mysql.TEXT(), nullable=False),
    sa.Column('fecha_creacion', sa.DATE(), nullable=False),
    sa.Column('estatus', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('id_proyecto', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_proyecto'], ['proyecto.id_proyecto'], name=op.f('fk_foros_proyecto')),
    sa.PrimaryKeyConstraint('id_foro'),
    mysql_collate='utf8mb3_general_ci',
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('foros', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('IDProyecto'), ['id_proyecto'], unique=False)

    op.create_table('encargado',
    sa.Column('IDEncargado', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False),
    sa.Column('Nombre', mysql.VARCHAR(length=35), nullable=False),
    sa.Column('AP', mysql.VARCHAR(length=35), nullable=False),
    sa.Column('AM', mysql.VARCHAR(length=35), nullable=False),
    sa.Column('Telefono', mysql.VARCHAR(length=14), nullable=False),
    sa.Column('Correo', mysql.VARCHAR(length=35), nullable=False),
    sa.Column('fecha_creacion', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=True),
    sa.Column('fecha_modificacion', mysql.DATETIME(), server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'), nullable=True),
    sa.PrimaryKeyConstraint('IDEncargado'),
    mysql_collate='utf8mb3_general_ci',
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    op.create_table('usuarios_proyecto',
    sa.Column('id_usuario_proyecto', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False),
    sa.Column('id_usuario', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False),
    sa.Column('id_proyecto', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_proyecto'], ['proyecto.id_proyecto'], name=op.f('fk_usuarios_proyecto_proyecto')),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], name=op.f('fk_usuarios_proyecto_usuario')),
    sa.PrimaryKeyConstraint('id_usuario_proyecto'),
    mysql_collate='utf8mb3_general_ci',
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('usuarios_proyecto', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('IDUsuarios'), ['id_usuario'], unique=False)
        batch_op.create_index(batch_op.f('IDProyecto'), ['id_proyecto'], unique=False)

    op.create_table('eventos',
    sa.Column('id_evento', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False),
    sa.Column('nombre', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('tipo_evento', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('fecha_inicio', sa.DATE(), nullable=False),
    sa.Column('fecha_fin', sa.DATE(), nullable=False),
    sa.Column('lugar', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('id_institucion', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False),
    sa.Column('aforo_maximo', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('fecha_creacion', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=True),
    sa.Column('fecha_modificacion', mysql.DATETIME(), server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'), nullable=True),
    sa.ForeignKeyConstraint(['id_institucion'], ['institucion.id_institucion'], name=op.f('fk_eventos_institucion')),
    sa.PrimaryKeyConstraint('id_evento'),
    mysql_collate='utf8mb3_general_ci',
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('eventos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('IDInstitucion'), ['id_institucion'], unique=False)

    op.create_table('institucion_insumo',
    sa.Column('id_inst_insumo', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False),
    sa.Column('id_institucion', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False),
    sa.Column('id_insumo', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False),
    sa.Column('existencia', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_institucion'], ['institucion.id_institucion'], name=op.f('fk_institucion_insumo_institucion')),
    sa.ForeignKeyConstraint(['id_insumo'], ['insumo.id_insumo'], name=op.f('fk_institucion_insumo_insumo')),
    sa.PrimaryKeyConstraint('id_inst_insumo'),
    mysql_collate='utf8mb3_general_ci',
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('institucion_insumo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('IDInsumo'), ['id_insumo'], unique=False)
        batch_op.create_index(batch_op.f('IDInstitucion'), ['id_institucion'], unique=False)

    # ### end Alembic commands ###
